# For more information: https://laravel.com/docs/sail
version: '3'

services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-www-data}'
    image: sail-8.0/app
    container_name: hackgreenville
    ports:
      - '${APP_PORT:-80}:80'
    env_file:
      - .env
    volumes:
      - './:/var/www/html'
    depends_on:
      - hackgreenville-db
   
  # If you change this service name, remember to change the
  # DB_HOST environment variable to match!
  hackgreenville-db:
    image: 'mysql:8.0'
    container_name: hackgreenville-db
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - './mysql:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]